### ISSUE TITLE
Switching to LCEL

### ISSUE THREAD

**Issue by magedhelmy1** [pamelafox/python-openai-demos#2]
```
- [ ] bug report -> please search issues before submitting
- [ ] feature request
- [X] documentation issue or request
- [ ] regression (a behavior that used to work and stopped in a new release)
```
Dear Pamela,

Thank you for the excellent work across all your repositories. It's truly inspiring and rich in content. I was wondering if there is a plan to switch to [LCEL](https://python-langchain-com.translate.goog/docs/expression_language/why?_x_tr_sl=en&_x_tr_tl=no&_x_tr_hl=no&_x_tr_pto=sc&_x_tr_hist=true) to reduce code complexity?

Best regards,
Maged

**Comment by pamelafox** [comment]
I've added a langchain example to demonstrate the very basic Langchain usage (which has a single LCEL expression). I intentionally use the OpenAI SDK in these examples to complement my slides at https://pamelafox.github.io/my-py-talks/llms-python/ but I do like to be able to show other frameworks as well.
